thegeeklab/ansible-doctor

- CHANGELOG.md
- ansibledoctor/DocumentationParser.py
- ansibledoctor/Utils.py
Fix for https://github.com/xoxys/ansible-doctor/issues/4
> add custom yaml constructor to load ansible unsafe tag

- CHANGELOG.md
- ansibledoctor/Annotation.py
Fix https://github.com/xoxys/ansible-doctor/issues/6
> remove only first hashtag from a multiline comment

- ansibledoctor/cli.py
- ansibledoctor/config.py
- ansibledoctor/doc_parser.py
Renaming my branch causes the closure of my last pull request
> feat: add new CLI flag --no-role-detection to parse loose files

- ansibledoctor/doc_generator.py
- ansibledoctor/templates/hugo-book/_meta.j2
- ansibledoctor/templates/hugo-book/_toc.j2
- ansibledoctor/templates/hugo-book/_vars.j2
- ansibledoctor/templates/readme/_meta.j2
- ansibledoctor/templates/readme/_toc.j2
- ansibledoctor/templates/readme/_vars.j2
- example/README.md
- example/demo-role/defaults/main.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/20
> fix: allow line-breaks in multiline annotations

- ansibledoctor/doc_parser.py
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/3
> fix: preserve multiline string formatting

- ansibledoctor/config.py
- ansibledoctor/doc_parser.py
- ansibledoctor/templates/hugo-book/_tag.j2
- ansibledoctor/templates/hugo-book/_toc.j2
- ansibledoctor/templates/hugo-book/index.md.j2
- ansibledoctor/templates/readme/README.md.j2
- ansibledoctor/templates/readme/_tag.j2
- ansibledoctor/templates/readme/_toc.j2
- ansibledoctor/utils.py
- docs/content/usage/getting-started.md
- example/README.md
- example/demo-role/tasks/main.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/22
> feat: auto-discover tags and add annotation identifier

- ansibledoctor/doc_parser.py
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/32
> fix: catch duplicate key error on yaml load

- docs/content/usage/getting-started.md
- example/README.md
- example/demo-role/defaults/main.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/280
> docs: add instrictions how to use the $ operator

- ansibledoctor/templates/readme/_meta.j2
- example/README.md
- example/demo-role/meta/main.yml
Supersedes: https://github.com/thegeeklab/ansible-doctor/pull/299
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/298
> fix: get role name from dependencies in case of a dictionary

- .dictionary
- .pre-commit-hooks.yaml
- docs/content/usage/configuration.md
The initial work was done by https://github.com/thegeeklab/ansible-doctor/pull/21 As this was requested multiple times now I changed my mind and picked it up again. Thanks for the initial PR!
> feat: add pre-commit support

- ansibledoctor/templates/hugo-book/_vars.j2
- ansibledoctor/templates/hugo-book/index.md.j2
- ansibledoctor/templates/readme/README.md.j2
- ansibledoctor/templates/readme/_vars.j2
- example/other-role/README.md
- example/other-role/meta/main.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/456
> fix: fix map filter used for meta description

- ansibledoctor/templates/hugo-book/index.md.j2
- ansibledoctor/templates/readme/README.md.j2
Update `_tag.j2` include block comment from "_Todo_" to "_Tag_" in `hugo-book/index.md.j2` and `README.md.j2` to provide a more accurate description of the code.
> update comment from "Todo" to "Tag"

- poetry.lock
- pyproject.toml
Ref: `https://github.com/charliermarsh/ruff/issues/2923#issuecomment-1431511636`
> chore: exclude ruff linter rule UP038

- ansibledoctor/utils/yamlhelper.py
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/604
> fix: skip missing yaml file

- .pre-commit-hooks.yaml
- docs/content/usage/configuration.md
On fresh install:
```
ERROR: Python requirements are missing: 'ansible-core' not found.
```
> fix: install extra group  when using pre-commit

- ansibledoctor/templates/hugo-book/_meta.j2
- ansibledoctor/templates/hugo-book/_tag.j2
- ansibledoctor/templates/hugo-book/_todo.j2
- ansibledoctor/templates/hugo-book/index.md.j2
- ansibledoctor/templates/readme/README.md.j2
- ansibledoctor/templates/readme/_meta.j2
- ansibledoctor/templates/readme/_tag.j2
- ansibledoctor/templates/readme/_todo.j2
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/867
> fix: avoid extra empty newlines on outout

- docs/content/development/_index.md
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/476
> docs: add basic developer docs

- ansibledoctor/cli.py
- ansibledoctor/config.py
- ansibledoctor/doc_generator.py
- docs/content/usage/configuration.md
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/690
> feat: support custom output files

- ansibledoctor/annotation.py
- ansibledoctor/config.py
- docs/content/usage/configuration.md
- example/demo-role/.ansibledoctor.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/785
> feat: support custom annotation subtypes

- ansibledoctor/config.py
- ansibledoctor/doc_generator.py
- ansibledoctor/doc_parser.py
- ansibledoctor/templates/hugo-book/_vars.j2
- ansibledoctor/templates/hugo-book/_vars_tabulated.j2
- ansibledoctor/templates/hugo-book/index.md.j2
- ansibledoctor/templates/readme/README.md.j2
- ansibledoctor/templates/readme/_vars.j2
- ansibledoctor/templates/readme/_vars_tabulated.j2
- example/demo-role/README.md
- example/demo-role/defaults/main.yml
- example/demo-role/meta/argument_specs.yml
Fixes: https://github.com/thegeeklab/ansible-doctor/issues/763
> feat: add basic support to parse argument specs
